color0       #3C3A39
color8       #93A098
color1       #8D927A
color9       #8D927A
color2       #B39068
color10      #B39068
color3       #B8B96A
color11      #B8B96A
color4       #45D7D8
color12      #45D7D8
color5       #F7C781
color13      #F7C781
color6       #B7DAC5
color14      #B7DAC5
color7       #D3E4DA
color15      #D3E4DA